### ISSUE TITLE
App's Crashing

### ISSUE THREAD

**Issue by HackCocaine** [MehmetEfeFriday/FRIDA-ART-FIX#2]
Hello! I just copied the frida-server for my ARM, but apps are crashing. I'm probably doing it wrong, can you elaborate a little more in how to use the files you shared? Do i need to copy all of them, if so, into what folders?

Thanks mate!

**Comment by MehmetEfeFriday** [comment]
Some devices may experience crashing issues with the Frida server because the fix from Matbrik is not yet stable. If you are using a gadget, you can get more reliable results. this Frida server currently has many issues, so as a temporary solution, it would be better to try the official server version of Frida by entering this command:
```pm uninstall com.google.android.art```
